---
abstract: 'transform JSON using JsonT'
author:
  - 'Stefan Goessner'
  - 'Toby Inkster'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - ECMAScript
  - JSON
  - JavaScript
  - JsonT
  - Transform
license: lgpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JSON::T
name: JSON-T
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  JavaScript::SpiderMonkey: 0
requires:
  Class::Load: 0
  JE: 0
  JSON: 2.00
  Object::AUTHORITY: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-T
  homepage: https://metacpan.org/release/JSON-T
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: https://bitbucket.org/tobyink/p5-json-t
version: 0.102
