---
abstract: 'transform JSON using JsonT'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::11 version , CPAN::Meta::Converter version 2.140640'
keywords:
  - ECMAScript
  - JSON
  - JavaScript
  - JsonT
  - Transform
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-T
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  JSON::T:
    file: lib/JSON/T.pm
    version: '0.103'
  JSON::T::JE:
    file: lib/JSON/T/JE.pm
    version: '0.103'
  JSON::T::SpiderMonkey:
    file: lib/JSON/T/SpiderMonkey.pm
    version: '0.103'
recommends:
  JavaScript::SpiderMonkey: '0'
requires:
  Class::Load: '0'
  JE: '0'
  JSON: '2.00'
  Object::AUTHORITY: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/JSON-T/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-T
  homepage: https://metacpan.org/release/JSON-T
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: git://github.com/tobyink/p5-json-t.git
version: '0.103'
x_contributors:
  - 'Stefan Goessner'
